server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/bug_tracker
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:

  spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/bug_tracker
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.show-sql= true